### ISSUE TITLE
Wrong API deployment memory limit?

### ISSUE THREAD

**Issue by migmartri** [kubernetes-helm/monocular#252]
In some cases during initial boot I get the container killed flagged as `OOMKilled`

We should either tweak that value, remove it or allow customization.

**Comment by Angelmmiguel** [comment]
Is this related to image processing? Maybe we can reduce the number of threads that process the images.

**Comment by prydonius** [comment]
@migmartri are you still seeing this?

**Comment by prydonius** [comment]
Closing this, @migmartri please reopen if you see this again.
