### ISSUE TITLE
Hide charts marked as deprecated

### ISSUE THREAD

**Issue by prydonius** [kubernetes-helm/monocular#254]
Helm now has support for marking charts as deprecated in the [chart metadata](https://github.com/kubernetes/helm/blob/master/docs/charts.md#deprecating-charts).

In Monocular we should process this field to prevent deprecated charts from showing up, e.g.: https://kubeapps.com/charts/search?q=lego

**Comment by Angelmmiguel** [comment]
@prydonius do you think we should hide them or place them to the bottom and add a "deprecated" label?

**Comment by prydonius** [comment]
Given that there are not many charts, I would just hide them. It might be better to have a toggle to show deprecated charts.
