### ISSUE TITLE
Monocular UI pod fails to launch

### ISSUE THREAD

**Issue by dcberg** [kubernetes-helm/monocular#263]
I'm using master and helm to install monocular. The monocular-ui pod fails to launch.

Readiness probe failed: Get http://172.30.226.22:80/: dial tcp 172.30.226.22:80: getsockopt: connection refused
Back-off restarting failed docker container
Error syncing pod, skipping: failed to "StartContainer" for "monocular" with CrashLoopBackOff: "Back-off 10s restarting failed container=monocular pod=terrifying-ocelot-monocular-ui-551467507-7q2lr_default(0fcaebd6-422a-11e7-b52f-d2987996dc93)"

**Comment by prydonius** [comment]
@dcberg sorry, missed this. What are the logs from the failed container?

**Comment by prydonius** [comment]
ping @dcberg any more info on this?

**Comment by todkap** [comment]
I have seen this as well. What I did to work around this was to continue to delete the failing POD until eventually the two instances both came up and were running.  Looks like it is attempting to load a large set of resources when starting up.

> time="2017-06-16T19:19:34Z" level=info msg="Processing icon" dest="/root/monocular/repo-data/stable/gitlab-ce/0.1.8/logo-160x160-fit.png" source="/root/monocular/repo-data/stable/gitlab-ce/0.1.8/logo-original.png" 
> time="2017-06-16T19:19:34Z" level=info msg="Local cache missing" name=magento version=0.4.3 
> time="2017-06-16T19:19:34Z" level=info msg="Downloading metadata" dest="/root/monocular/repo-data/stable/magento/0.4.3/chart.tgz" source="https://kubernetes-charts.storage.googleapis.com/magento-0.4.3.tgz" 
> time="2017-06-16T19:19:34Z" level=info msg="Local cache missing" name=magento version=0.4.2 
> time="2017-06-16T19:19:34Z" level=info msg="Downloading metadata" dest="/root/monocular/repo-data/stable/magento/0.4.2/chart.tgz" source="https://kubernetes-charts.storage.googleapis.com/magento-0.4.2.tgz" 
> time="2017-06-16T19:19:34Z" level=info msg="Storing in cache" path="/root/monocular/repo-data/stable/testlink/0.4.3/README.md" 
> time="2017-06-16T19:19:34Z" level=info msg="Local cache missing" name=magento version=0.4.1 
> time="2017-06-16T19:19:34Z" level=info msg="Downloading metadata" dest="/root/monocular/repo-data/stable/magento/0.4.1/chart.tgz" source="https://kubernetes-charts.storage.googleapis.com/magento-0.4.1.tgz" 
> time="2017-06-16T19:19:34Z" level=info msg="Downloading icon" dest="/root/monocular/repo-data/stable/testlink/0.4.7/logo-original.png" source="https://bitnami.com/assets/stacks/testlink/img/testlink-stack-220x234.png" 
> time="2017-06-16T19:19:34Z" level=info msg="Processing icon" dest="/root/monocular/repo-data/stable/spark/0.1.3/logo-160x160-fit.png" source="/root/monocular/repo-data/stable/spark/0.1.3/logo-original.png" 
> time="2017-06-16T19:19:34Z" level=info msg="Processing icon" dest="/root/monocular/repo-data/stable/gitlab-ce/0.1.7/logo-160x160-fit.png" source="/root/monocular/repo-data/stable/gitlab-ce/0.1.7/logo-original.png" 
> time="2017-06-16T19:19:34Z" level=info msg="Local cache missing" name=magento version=0.4.0 
> time="2017-06-16T19:19:34Z" level=info msg="Downloading metadata" dest="/root/monocular/repo-data/stable/magento/0.4.0/chart.tgz" source="https://kubernetes-charts.storage.googleapis.com/magento-0.4.0.tgz"

**Comment by prydonius** [comment]
@todkap indeed, you may need to increase the initial delay for the liveness probe: https://github.com/kubernetes-helm/monocular/blob/master/deployment/monocular/values.yaml#L23
