### ISSUE TITLE
UI is showing reloading but not showing any charts

### ISSUE THREAD

**Issue by amanscollection** [kubernetes-helm/monocular#274]
Hi team,

I am deploying monocular using helm charts and able to access the UI using monocular UI service.

Issues-:
1) Ingress is implemented but controller URl is not redirecting to monocular UI
2) accessing monocular UI using monocular Nodeport Service and that too just showing loading.
3)in config section of values.yaml, not sure what to enter in backend part and it is commented.
appName: Monocular
  # backendHostname: http://monocular-api.local

**Comment by prydonius** [comment]
Hey @amanscollection,

Did you set an ingress host? If you left it as the default, then the nginx controller external IP should redirect to Monocular (though you may see a self-signed SSL cert error).

If you want to access the UI and API from their node ports, you can do the following:
```
$ kubectl edit configmap $RELEASE_NAME-monocular-api-config
```

Add or change `my-api-server` to the node ip and port for your UI service, e.g. `http://<ip>:<port>`. This configures the API to allow requests from this hostname.

Similarly, modify the UI configuration to point to the node ip and port for your API service:
```
$ kubectl edit configmap $RELEASE_NAME-monocular-ui-config
```

Add `backendHostname` to the overrides object in the config:

```
data:
  overrides.js: |-
    window.monocular = {
      overrides: {
        googleAnalyticsId: 'UA-XXXXXX-X',
        appName: 'Monocular',
        releasesEnabled: true,
        backendHostname: "http://<ip>:<port>"
      }
    };
```

After editing these, kill your API and UI pods to have them restart with this updated configuration.

**Comment by iftachsc** [comment]
hi. i'm encountering the same issue.
was it solved? amanscollection  did you try?

**Comment by amanscollection** [comment]
Hi,

I have not yet tried. But will check soon and revert.

**Comment by iftachsc** [comment]
i've done it. now the client goes to the correct place - gets 200ok.
if i copy the request url from the client developer tools to another tab - also works - i get the charts from the api service. but when the app issues this request i get:
**No 'Access-Control-Allow-Origin' header is present on the requested resource.**

![image](https://user-images.githubusercontent.com/28829551/27529850-bd85d856-5a5e-11e7-8d3f-30bf248cfe40.png)

UI is still presenting the animation of loading forever

**Comment by prydonius** [comment]
@iftachsc have you configured CORS on the backend? Note that you need to configure the `allowed_origins` parameter. See https://github.com/helm/monocular/tree/master/deployment/monocular#serve-monocular-frontend-and-api-on-different-domains for an example.

**Comment by prydonius** [comment]
@iftachsc let me know if you're still having issues setting this up
