### ISSUE TITLE
Question: How to deploy privately or with authentication 

### ISSUE THREAD

**Issue by rjminsha** [kubernetes-helm/monocular#289]
Is there a best practice for deploying monocular with either authentication, or not on ingress?

**Comment by prydonius** [comment]
Hey @rjminsha,

You can read about deploying Monocular without ingress here https://github.com/helm/monocular/tree/master/deployment/monocular#serve-monocular-frontend-and-api-on-different-domains.

Authentication is something we're thinking about (#258), if you have any thoughts on that, that would be great. In the meantime, it's possible to setup simple authentication using the Ingress controller https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#authentication

**Comment by rjminsha** [comment]
@prydonius thanks!  Will work through those and follow the Issue.

**Comment by prydonius** [comment]
@rjminsha feel free to reopen/create another issue if you have any more questions
