### ISSUE TITLE
Monocular Deployment fails with "failed to connect to tiller" even though Tiller service is running in the cluster

### ISSUE THREAD

**Issue by kirtiapte** [kubernetes-helm/monocular#290]
I have tiller  service installed in the Kubernetes cluster.  
kube-system   tiller                               <nodes>           2h

I have installed monocular in two node cluster and could access UI and repos.  But deployment is failing with 
Can't create the release: failed to connect to Tiller, are you sure it is installed?

**Comment by kirtiapte** [comment]
Looks like tiller service name is hardcoded to tiller-deploy.  In my case service name is tiller.  Could those be configurable values?

**Comment by prydonius** [comment]
@kirtiapte how did you create the service? AFAIK `helm init` will create one called `tiller-deploy`. We could make the service name configurable.

**Comment by prydonius** [comment]
@kirtiapte I believe this was because the API was based off an older version of alpine that didn't support DNS resolution. This has now been fixed.
