### ISSUE TITLE
moncular-ui - does not have any active endpoints

### ISSUE THREAD

**Issue by DawidCh** [kubernetes-helm/monocular#292]
Hello.
I'm new in k8s so it is probably my fault. I have installed nginx ingress from the chart https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress and after that I have installed monocular from charts. I'm facing a problem now, that controller for ingress nginx cries that monocular-ui and monocular-api services doesn't have active endpoints. I'm using kubernetes installed on ubuntu. I can connect to monocular UI using port from POD directly (`<k8sHost>:<monocular-uiPodPort>`), but I only see the header, the footer of the pages and "busy icon", which spins forever. Do you have an idea where I may search for a mistakes?
Regards, Dawid.
Ps. When I have done the same steps on GCE monocular works like a charm.

**Comment by DawidCh** [comment]
I have configured everything as it should be done (I'm getting to monocular using ingress addresses). Now I have following js error:
Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.

**Comment by prydonius** [comment]
Hi @DawidCh, is there a stacktrace for the JS error? How did you end up solving the issue with the no active endpoints?

**Comment by DawidCh** [comment]
Hi.
This is js error.
Regarding no active endpoints I do not know. I have tried many things so I can't tell the one which fixed that, sorry.

**Comment by prydonius** [comment]
@DawidCh any chance you could add a screenshot of the error with the page?

**Comment by DawidCh** [comment]
Sure. Let me just install it again.

**Comment by DawidCh** [comment]
Hi. It was problem with my kubernetes. My pod with kube-dns was failing from time to time and routing didn't work correctly. When I have fixed that, monocular works.
Thanks for support.
