### ISSUE TITLE
Cannot add the monocular repo

### ISSUE THREAD

**Issue by dcieslak19973** [kubernetes-helm/monocular#307]
Running:

helm repo add monocular https://helm.github.io/monocular

Error: Looks like "https://helm.github.io/monocular" is not a valid chart repository or cannot be reached: Failed to fetch https://helm.github.io/monocular/index.yaml

**Comment by prydonius** [comment]
Hey @dcieslak19973 

The repository was recently moved to a different org so you should run 
```
helm repo add https://kubernetes-helm.github.io/monocular/index.yaml
```

There are PRs #305 and #306 to update the documentation

**Comment by dcieslak19973** [comment]
Thanks. I'm able to add the repo. Now doing:

helm fetch monocular/monocular

gives:

Error: Failed to fetch https://helm.github.io/monocular/monocular-0.4.4.tgz

**Comment by dove-young** [comment]
I've got the same error, not found monocular package.

``
helm install monocular/monocular --debug
[debug] Created tunnel using local port: '34093'

[debug] SERVER: "localhost:34093"

[debug] Original chart version: ""
Error: Failed to fetch https://helm.github.io/monocular/monocular-0.4.4.tgz : 404 Not Found
```

**Comment by blaze33** [comment]
Yes, it seems like https://github.com/kubernetes-helm/monocular/blob/gh-pages/index.yaml is not yet updated to reflect the repository move

**Comment by prydonius** [comment]
Thanks for pointing it out @dove-young and @blaze33, I've updated #306 to fix this

**Comment by prydonius** [comment]
This should now be fixed, @dove-young @blaze33, let me know if it's not the case.

**Comment by blaze33** [comment]
@prydonius I can confirm it works, thanks
