### ISSUE TITLE
Show version number in the home page

### ISSUE THREAD

**Issue by arapulido** [kubernetes-helm/monocular#316]
Now that we have a release process,  it would be useful if we had the version number in the home page.

For example, in the footer we have:

"Monocular is an Open Source project"

We could say something

"This site  is running Monocular v0.3.0
Monocular is an Open Source project"

**Comment by prydonius** [comment]
I was thinking about showing the version too, thanks @arapulido! @kemcake @Angelmmiguel any ideas around placement?

**Comment by Angelmmiguel** [comment]
I agree with @arapulido, the footer is a good place to display the deployed version of the project :)

![screen shot 2017-08-16 at 15 07 18](https://user-images.githubusercontent.com/4056725/29364693-a252e53e-8294-11e7-931a-a050456c8631.png)

**Comment by prydonius** [comment]
thanks @Angelmmiguel, I like the mockup!
