### ISSUE TITLE
dns is normal,but only containers of  monocular  can't resolve  service name

### ISSUE THREAD

**Issue by mistyle** [kubernetes-helm/monocular#320]
monocular   has installed, but  find 3 problem，all related of dns ,serivce name, 

    for example，visit "http://xxxx/api/v1/releases" ,show the log
"failed to connect to Tiller, are you sure it is installed" ,in the pod log,show " grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup tiller-deploy.kube-system on 202.96.128.86:53: no such host"; Reconnecting to {tiller-deploy.kube-system:44134 }"
in the kubernetes master,when i execute the command " kubectl exec busybox -- nslookup tiller-deploy.kube-system" , show the message ,

"Server: 192.168.4.100
Address 1: 192.168.4.100

Name: tiller-deploy.kube-system
Address 1: 192.168.4.56
". ,the show dns is normal,why monocular api containers can't resolve svc of kubernetes(ui container and prerender container is normal)?

**Comment by prydonius** [comment]
Hmm, something is strange here. I'm able to reproduce this in the API container:

```
/ # nslookup tiller-deploy.kube-system
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'tiller-deploy.kube-system': Name does not resolve
```

However, for me, Monocular is still able to connect to the service, and actually, I can look it up by the full address:

```
/ # nslookup tiller-deploy.kube-system.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      tiller-deploy.kube-system.svc.cluster.local
Address 1: 100.66.20.21 tiller-deploy.kube-system.svc.cluster.local
```

Could you try looking it up with the full address?

What are you using for your networking?

**Comment by mistyle** [comment]
yes! when  i  execute  "nslookup tiller-deploy.kube-system.svc.cluster.local",the Address  1 is no normal.like this “
/ # nslookup tiller-deploy.kube-system
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'tiller-deploy.kube-system': Name does not resolve
/ # nslookup tiller-deploy.kube-system.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      tiller-deploy.kube-system.svc.cluster.local
Address 1: 192.168.4.56
/ #"
In addition,visit "http://xxxx/api/v1/releases" ,also normal,I do not know what I am doing，so amazing!
very  thank you!but for  my English is not good, I think I will often come to this site。
