### ISSUE TITLE
Mobile visualization issue

### ISSUE THREAD

**Issue by migmartri** [kubernetes-helm/monocular#325]
It seems that the UI has some glitches with its mobile version.

Home page:

![screenshot_20170721-175407](https://user-images.githubusercontent.com/24523/28487016-088b6486-6e3e-11e7-8515-c81a3cdda653.png)

![screenshot_20170721-175401](https://user-images.githubusercontent.com/24523/28487015-05f0298c-6e3e-11e7-966a-31af39f2920e.png)

Charts listing
![screenshot_20170721-175423](https://user-images.githubusercontent.com/24523/28487025-13d0ccbe-6e3e-11e7-8c47-d8e719832701.png)

Chart page

![screenshot_20170721-175441](https://user-images.githubusercontent.com/24523/28487026-1a5e590c-6e3e-11e7-8025-f5e2ef629e97.png)

![screenshot_20170721-175446](https://user-images.githubusercontent.com/24523/28487027-1d1564e2-6e3e-11e7-8ae9-57b209d458c5.png)

OS: Android
Browser: Chrome 59.03

**Comment by kemcake** [comment]
Most of these should be fixed with #319  🙌 

except maybe the last one on chart-detail

**Comment by prydonius** [comment]
@kemcake thanks, I merged #319. Are you able to take on the chart-detail page?

**Comment by kemcake** [comment]
@prydonius done in #328 💪
