### ISSUE TITLE
 swagger-ui visit swagger.yml file in the  monocular 

### ISSUE THREAD

**Issue by mistyle** [kubernetes-helm/monocular#326]
I have installed monocular, now want to visit monocular api interface  by  the swagger-ui , I noticed in the monocular source code has a swagger.yml, how can direct access to the deployment of monocular applications swagger.yml? 
        For example, monocular ui's first page is http: //192.168.56.100, so then swagger.yml file path is "http://192.168.56.100/swagger.yml"?  or " http://192.168.56.100/api/swagger.yml ? or others? 
Did anyone know?

**Comment by mistyle** [comment]
Did anyone know?

**Comment by prydonius** [comment]
@mistyle the swagger ui is not meant to be exposed via the API. You can load it into a swagger UI viewer if you wish you view it.
