### ISSUE TITLE
Allow specifying a namespace other than "default" when creating deployments

### ISSUE THREAD

**Issue by arapulido** [kubernetes-helm/monocular#327]
Right now, when creating deployments with Monocular, it is not possible to specify the namespace, so all deployments happen in the default namespace.

It would be good to be able to specify a different namespace

**Comment by prydonius** [comment]
Should Monocular show existing namespaces, or just provide a textbox to enter the name of the namespace? Although a dropdown of existing namespaces would be nice, it means Monocular will require special RBAC permissions to query the Kubernetes API for namespaces. A textbox doesn't require this as it will just be passed to Tiller.

In the future, we want to add the ability to view/modify resources created by Monocular, so eventually we will require RBAC permissions, I think it's just a question of whether we do this sooner or later.
