### ISSUE TITLE
Problem adding repo (404)

### ISSUE THREAD

**Issue by cabrinoob** [kubernetes-helm/monocular#346]
Hi,
I'am trying to add a private repo that I'am already using in production (so it works with helm, no problem). This repo is deployed on S3.

But when I add it in monocular and when I go to the charts page, it fails with this error in chrome console : 

    Failed to load resource: the server responded with a status of 404 ()
    charts.service.ts:150 404 - OK
    t.handleError @ charts.service.ts:150
    error_handler.js:50 EXCEPTION: 404 - OK
    t.handleError @ error_handler.js:50
    Subscriber.js:227 Uncaught 404 - OK
    /api/v1/charts/at-charts Failed to load resource: the server responded with a status of 404 ()
    charts.service.ts:150 404 - OK
    t.handleError @ charts.service.ts:150

And in the Monocular-api pod logs : 

    2017/08/30 06:30:42 data.Charts AllFromRepo(at-charts) error (no charts found for repo at-charts)

I tried to see the differences between incubator or stable repo and my repo but I don't see something very important except perhaps the \<OWNER\> tag : 

Here's a sample of my repo XML :

```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>at-helm-charts</Name>
    <Prefix/>
    <Marker/>
    <MaxKeys>1000</MaxKeys>
    <IsTruncated>false</IsTruncated>
    <Contents>
        <Key>index.yaml</Key>
        <LastModified>2017-08-28T13:44:33.000Z</LastModified>
        <ETag>"5f637af4c3ce87f88a03bf177a591ae4"</ETag>
        <Size>5639</Size>
        <Owner>
            <ID>
                aefd209a1f4bf9ef86dd13477267607df5b62eddbdea2652137502a98267df6d
            </ID>
            <DisplayName>amazondev</DisplayName>
         </Owner>
         <StorageClass>STANDARD</StorageClass>
    </Contents>
    <Contents>
        <Key>my-chart-0.1.2.tgz</Key>
        <LastModified>2017-08-22T09:00:03.000Z</LastModified>
        <ETag>"f3c27dc4f4588d2cbd3f4e4591545d9b"</ETag>
        <Size>2431</Size>
        <Owner>
            <ID>
                aefd209a1f4bf9ef86dd13477267607df5b62eddbdea2652137502a98267df6d
            </ID>
            <DisplayName>amazondev</DisplayName>
         </Owner>
         <StorageClass>STANDARD</StorageClass>
     </Contents>
...
```

Thank you for your <s>helm</s> help

**Comment by prydonius** [comment]
Hey @cabrinoob, if you added the repository in the UI you will need to wait till the next refresh cycle for charts to show up (currently this doesn't happen straight away, see #344). By default this is every hour but you can change this with this value: https://github.com/kubernetes-helm/monocular/blob/master/deployment/monocular/values.yaml#L48.

If you added it via the config file, check the logs during startup as it refreshes the repository. Your charts will be skipped if they don't have a README.

**Comment by cabrinoob** [comment]
Ok, I've changed the refresh rate and it worked. 
Thank you!
