### ISSUE TITLE
Use Kubernetes for Repo Storage

### ISSUE THREAD

**Issue by osoriano** [kubernetes-helm/monocular#351]
I'm interested in using Kubernetes (maybe CRDs or ConfigMaps) for Monocular repo storage. 

My current environment doesn't have PVCs configured. Kubernetes storage could be an alternative in this case.

**Comment by prydonius** [comment]
I think this will get complicated when we start dealing with different types of data (charts, auth, ratings/comments of charts). A database is much better suited for the type of data we will want to be storing.

**Comment by osoriano** [comment]
Sounds like Kubernetes storage won't be a good solution for the long-term goals of this project (charts, auth, ratings/comments). I'll close the issue for now, thanks
