### ISSUE TITLE
chart-item width issue

### ISSUE THREAD

**Issue by jaohaohsuan** [kubernetes-helm/monocular#360]
Thanks to your hard working. It's a great project. 👍 

I found a problem which is chart-item width narrow down when in full screen of the browser.

<img width="1361" alt="screen shot 2017-09-24 at 12 22 51 am" src="https://user-images.githubusercontent.com/1515130/30775026-9dc52902-a051-11e7-9c8a-75b646458552.png">

The problem founds in `v0.4.0` and the `latest` version of docker image.
Any ideas?

**Comment by prydonius** [comment]
Hey @jaohaohsuan!

Strange, what browser and version are you using? /cc @kemcake

**Comment by jaohaohsuan** [comment]
Thanks  @prydonius 
I am using Chrome `Version 61.0.3163.100 (Official Build) (64-bit)` on macos  10.12.6.

That only two or few charts will occur the problem I guess.

**Comment by prydonius** [comment]
Are you also seeing this issue on https://kubeapps.com? It looks like you're using a custom repository, is this internal or something I can test with?

**Comment by jaohaohsuan** [comment]
This is my custom repository below you can test with.

```
url: https://jaohaohsuan.github.io/helm-charts
source: https://github.com/jaohaohsuan/helm-charts/tree/master/incubator
```

**Comment by kemcake** [comment]
Ok I identified the issue, it's just on the home page when we have only a few charts, the container view doesn't stretch to fill the page. I will fix it 👍
