### ISSUE TITLE
Cant work properly because redis

### ISSUE THREAD

**Issue by felixPG** [kubernetes-helm/monocular#363]
Hi:

Make the installation of monocular keep the REDIS POD always in pending status, the cause is that redis chart by default use StorageClasss but NOT all people have or want dynamic provisioning in our k8s cluster. Please, could you add in values.yaml the option to specify the redis server in orther to deploy our custom redis server based in NFS or HOSTPATH, etc ?????

How I could solve the problem using the standard **helm install monocular** and without redis pod in pending status?

**Comment by prydonius** [comment]
Hi @felixPG,

The chart should definitely support specifying a custom Redis host, I've created #364 for this.

In the meantime, you have 2 options:
- disable persistence in redis, pass the `redis.persistence.enabled=false` value
- create a default StorageClass in your cluster that is able to select a manually created PV

**Comment by felixPG** [comment]
thanks @prydonius , I see that in api-config.yaml is the only file where redis are specified in the monocular charts, correct? Only changing this value I could take monocular up but is a ugly solution, better change throught values.yaml
Regards

**Comment by prydonius** [comment]
I'll close this out in favour of #364
