### ISSUE TITLE
chart: support custom redis host

### ISSUE THREAD

**Issue by prydonius** [kubernetes-helm/monocular#364]
I should be able to provide a custom redis host to the chart on install. This should disable the redis dependency and instead configure Monocular to use the custom host.

see also #363

**Comment by prydonius** [comment]
@felixPG moving the discussion from #363 here:

A value could be added for this, e.g. `redisHost`, and then we could check for this in `api-config.yaml` and use `{{ template "redis.fullname" . }}:6379` as a default if redisHost is empty.

Also, we would need to disable the Redis chart dependency (see https://docs.helm.sh/developing_charts/#tags-and-condition-fields-in-requirements-yaml) so that if `redisHost` is defined, we don't deploy Monocular's Redis.

**Comment by felixPG** [comment]
Thanks so much @prydonius I will make the change in api-config for test purpose.

**Comment by prydonius** [comment]
If you're able to PR the change that would be awesome :)

**Comment by felixPG** [comment]
Sure, when I have a little time I will make the change.

**Comment by felixPG** [comment]
Hi @prydonius , after a little pause I make the following work:

1. Download the official redis chart, change the PVC to use my custom like NFS
2. Package with helm this custom chart of redis
3. Download monocular chart
4. Change requirements.yaml and specify a custom redis chart as file
5. Package custom monocular chart
6. Install my custome chart

After that all working ok, but appear that monocular cant see the redis server:

FROM LOGS:

**2017/09/27 16:13:07 Can not configure repository cache dial tcp 10.96.223.16:6379: getsockopt: connection refused.** 

Please, what the hell happend with monocular???

**Comment by felixPG** [comment]
Only to confirm, like a charm with specific redis host.

**Comment by prydonius** [comment]
@felixPG did you get this working?

**Comment by felixPG** [comment]
yeah!, Im now translating the UI to spanish, is possible to submit the translate as PR too?

**Comment by prydonius** [comment]
Oh nice, feel free to create another issue for that. Assuming you're using an i18n plugin for the translation I would be happy to accept a PR for that :)

**Comment by felixPG** [comment]
oh wait, I make manually the translation, then compiling and uploading in a private repo my custom image tu use in ui-deployment.yaml. When I have a little time I will make both PRs.

Regards
