### ISSUE TITLE
how to add chartmuseum repository to monocular

### ISSUE THREAD

**Issue by huydinhle** [kubernetes-helm/monocular#395]
Here is my section 
```
      - name: chartmuseum-charts
        url: http://chartmuseum-chartmuseum.chartmuseum.svc.cluster.local:8080/api/charts
        source: https://github.com/<org>/repo/master/helm/charts
```

which path should I have for the url section to make it works. I notice this one https://kubernetes-charts-incubator.storage.googleapis.com has xml response instead of json

**Comment by prydonius** [comment]
@huydinhle the URL should be the path that has the index.yaml file. E.g. https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml

**Comment by huydinhle** [comment]
thank you for answering it works
