### ISSUE TITLE
Adding Purge to Delete Deployment?

### ISSUE THREAD

**Issue by hertzknight** [kubernetes-helm/monocular#406]
Working with the API, I was wondering if you will be adding the purge feature when deleting deployments. My current project wants to names even after we delete them.

**Comment by prydonius** [comment]
It's a good idea. Although, if you're using Monocular just for the API I would suggest looking at something like https://github.com/appscode/swift or https://github.com/bitnami/helm-crd for a Kubernetes-native way to manage deployments.

Going forward, this project will switch to one of those methods and remove the releases API from Monocular.

**Comment by hertzknight** [comment]
Thanks for the additional information.
