### ISSUE TITLE
Where to download monocular helm chart source code?

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes-helm/monocular#407]
Hi, 

Is it possible to download monocular helm chart source code? I want to customize some settings for my own environment.

**Comment by prydonius** [comment]
Hey, certainly. The chart is here (https://github.com/kubernetes-helm/monocular/tree/master/deployment/monocular) or you can use `helm fetch monocular/monocular`

**Comment by hiscal2015** [comment]
Thanks a lot.
