### ISSUE TITLE
consul wont deploy on openshift

### ISSUE THREAD

**Issue by MansM** [kubernetes-helm/monocular#418]
default           14s        40m         99        aspiring-rabbit-consul                           StatefulSet                                             Warning   FailedCreate            statefulset                   create Pod aspiring-rabbit-consul-0 in StatefulSet aspiring-rabbit-consul failed error: pods "aspiring-rabbit-consul-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group]

Not entirely sure if this is a chart/openshift/monocular issue....

**Comment by prydonius** [comment]
hey @MansM, probably best to create an issue in https://github.com/kubernetes/charts/issues since this is a chart issue. It does also seem somewhat specific to OpenShift though.

**Comment by prydonius** [comment]
@MansM can we close this issue?

**Comment by MansM** [comment]
yeah
