### ISSUE TITLE
Adding private repository with basic auth

### ISSUE THREAD

**Issue by jonasdkhansen** [kubernetes-helm/monocular#428]
I want to add a private repository with basic auth, it could be a running chartmuseum with basic auth. I have tried to add https://Username:Password@mydomain.com but that isn't working.

**Comment by prydonius** [comment]
@jonasdkhansen any logs from the API pod that might indicate what's happening? Bear in mind you'll need to wait for the next sync cycle (up to 60 mins by default) for it to actually fetch charts from that repo.

**Comment by prydonius** [comment]
@jonasdkhansen np! FYI if you're looking for a similar experience, https://github.com/kubeapps/kubeapps doesn't have this issue as it has a different architecture to the Monocular API and kicks off Jobs to sync chart repos, meaning they'll sync as soon as you add them.
