### ISSUE TITLE
Can't retrieve deployments, because of wrong helm client and server version

### ISSUE THREAD

**Issue by jonasdkhansen** [kubernetes-helm/monocular#431]
I get this error from Monocular, and the deployment list in Monocular is empty.
`level=error msg="Can't retrieve the list of releases" error="rpc error: code = 2 desc = incompatible versions client[v2.2.0] server[v2.9.0-rc3]"`
I have upgraded helm client to v2.9.0.-rc3 on my computer and on my GKE cluster, and i have upgraded the tiller server in my cluster. Is Monocular using it's own client, when retrieving the deployment list?

**Comment by prydonius** [comment]
Monocular uses the Helm client library (https://github.com/kubernetes-helm/monocular/blob/master/src/api/data/helm/client/client.go#L11), it sounds like we'll just need to update the dependencies to pull a newer version of the client.

**Comment by jonasdkhansen** [comment]
Okay, thanks for the answer.

There isn't a workaround until the code is updated with the new version ?

**Comment by prydonius** [comment]
@jonasdkhansen probably not, apart from downgrading. Does it work with 2.8?

**Comment by jonasdkhansen** [comment]
@prydonius yes i works with 2.8, the problem is i need some functionality from the v2.9.0-rc1 :)

**Comment by prydonius** [comment]
@jonasdkhansen I'm not sure what's changed in 2.8-2.9 to stop this from working, it should in theory be backwards compatible. It might be because this is a release candidate, though.
