### ISSUE TITLE
No Charts Found for Repo

### ISSUE THREAD

**Issue by drekle** [kubernetes-helm/monocular#434]
I have a custom webserver which serves the index.yaml and package tar.gz's on `/`.  There is no signing done.  This webservice is running inside of kubernetes and uses a **traefik ingress controller** to route requests.

Below is this ingress for the helm server (names replaced)...
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
    traefik.frontend.rule.type: PathPrefixStrip
  name: myHelmIngress
  namespace: default
spec:
  rules:
  - host: helm.mysubdomain.mydomain.com
    http:
      paths:
      - backend:
          serviceName: myHelmService1
          servicePort: 80
        path: /stable
      - backend:
          serviceName: myHelmService2
          servicePort: 80
        path: /incubator
```
This ingress works with helm repo add via command line.  I can search and see my charts via the command line as well.

Below is the ingress for monocular. (names replaced)
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
    traefik.frontend.rule.type: PathPrefixStrip
  creationTimestamp: 2018-03-30T20:30:41Z
  generation: 7
  labels:
    app: chartsui-monocular
    chart: monocular-0.5.0
    heritage: Tiller
    release: chartsui
  name: chartsui-monocular
  namespace: default
  resourceVersion: "7666158"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/chartsui-monocular
  uid: 373700be-3459-11e8-bc05-00505692c6b7
spec:
  rules:
  - host: charts.mydomain.com
    http:
      paths:
      - backend:
          serviceName: chartsui-monocular-ui
          servicePort: 80
        path: /
      - backend:
          serviceName: chartsui-monocular-api
          servicePort: 80
        path: /api/
status:
  loadBalancer: {}
```
I have added the following repo in the ui (names replaced)
```
myRepo          https://helm.mysubdomain.mydomain.com/stable
```

https://helm.mysubdomain.mydomain.com/stable is behind a proxy and its structure looks something like this...
```
/
- index.yaml
- consul-1.3.2.tgz
- mongodb-0.4.27.tgz
```
the index.yaml references these tgz's as
https://helm.mysubdomain.mydomain.com/stable/mongodb-0.4.27.tgz
and if I visit this address the tgz will download.

the API logs the following message when attempting to filter on the charts from this added repo...
```
data.Charts AllFromRepo(myRepo) error (no charts found for repo myRepo
```

I have waited for the cache refresh interval #367 
Most, if not all, of my charts have a readme #370

The progress indicator spins forever.

Any thoughts on a resolution would be appreciated.

**Comment by prydonius** [comment]
Hey @drekle! Do you have logs from when the sync happened?

**Comment by drekle** [comment]
Hey @prydonius.  I have a repo running my service that does not appear to be creating any logs in the API.  I am probably going to switch to chartmuseum which will work and is preferable to something I threw together.  I am going to close this, you can continue to ping me if you want to chase down what was going wrong with mine, however I don't see a lot of other related issues on the backlog so its probably moot.

I can tell you I was basing mine off of the libraries in helm's github, around local repo.  I changed the serve address and anything needed to get it to work with the command line tool.
