### ISSUE TITLE
Passing the storage class to MongoDB

### ISSUE THREAD

**Issue by pkrishn6** [kubernetes-helm/monocular#437]
How to I set the pvc and pv details of mongoDb when I do 

`helm install --name my-release monocular`

Currently, I am pulling the mongoDb charts as a sub-charts. Setting the values and then installing monocular. Is that the only way to do it?

Thanks in advance for the help.

**Comment by skogie** [comment]
I had to add `storageclass.kubernetes.io/is-default-class: "true"` on the default storage class for dynamic volume provisioning to work correctly, I'm not sure if it will fix your problem tho. The default for mongodb is to use dynamic provisioning afaik.

**Comment by pkrishn6** [comment]
@skogie : Thanks for the response... 
When I look at the values.yaml of stable/mongoDB, default storageClassName is not set.

 ## mongodb data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

I am not worried about the default value. I am trying to deploy monocular to see if that is good fit for my needs on AWS instances. I do not use S3 and just want to provide hostPath as my pv. Wondering if there is a easier way to do than pulling the charts and setting the values..
