### ISSUE TITLE
Getting a basic deployment to work.

### ISSUE THREAD

**Issue by pkrishn6** [kubernetes-helm/monocular#440]
I am trying to deploy monocular on AWS EC2 instances . I set up nginx-ingress to use NodePort since I do not have a LB at my disposal right now and set ssl-redirect: "false" following the advice of @prydonius to avoid ssl redirects.

kubectl get ingress does not give an IP (expected)

but when I access monocular using the nodeIP:nodePort of nginx-ingress, the page loads but getting chart or repositories just circling around and not return anything.

If I access monocular using the nodeIp:nodePort of monocular-ui, I see the deployment, repos table but clicking on them does not retrieve my deployments. 

Any help on what I am doing wrong ?

**Comment by prydonius** [comment]
hey @pkrishn6, can you see any Javascript errors in your browser's console, or any failed requests in the network tab?

**Comment by pkrishn6** [comment]
@prydonius : Thanks for your response.

This is the error:
Request URL: http://xxxxx:32342/api/v1/repos
Request Method: GET
Status Code: 503 Service Temporarily Unavailable
Remote Address: xxxxxxxx:32342
Referrer Policy: no-referrer-when-downgrade

similar error for charts. Could this be a connectivity to mongoDb issue like #430  ?

I am unable to zero-in on the problem from kubectl logs of the api pod. I have just one api and one ui pod.
MongoDb set up with emptyDir
Ingress setup with nodePort .

**Comment by pkrishn6** [comment]
And interestingly, just deleting the values of "repos" key  in values.yaml was not sufficient to not download any repos.

// Enabled returns the map of repositories
func Enabled(configFile string) (Repos, error) {
	_, err := os.Stat(configFile)
	if os.IsNotExist(err) {
		log.Info("Loading default repositories")
		return official, nil
	}
        log.Info("Loading repositories from config file")
	repos, err := loadReposFromFile(configFile)
	if err != nil {
		return nil, err
	}

	if len(repos) == 0 {
		log.Info("No repositories found, using defaults")
		**return official, nil**      <-------- Here
	}
Looked at this code and though clearing the "repos" key from the values.yaml will do but that did not do the trick either.

loadReposFromFile I think does not return an err and hence official is returned. This pretty much gives users no option to disable official repos which I think is a bug

**Comment by prydonius** [comment]
@pkrishn6 it's "normal" for the API pod to restart many times as it downloads large Chart repos (like the stable one). Is it taking longer than 10 minutes to get to a running state?

**Comment by pkrishn6** [comment]
Was able to get the deployment to work.
*  ingress resource should have annotation:
nginx.ingress.kubernetes.io/rewrite-target: /       instead of 
ingress.kubernetes.io/rewrite-target: /    if the chart version of ingress-nginx is 0.17.1 or lower

Thanks @prydonius for all the help .

**Comment by prydonius** [comment]
@pkrishn6 this should now be fixed in the 0.5.1 chart version! thanks!
