### ISSUE TITLE
Realtime chart repo update

### ISSUE THREAD

**Issue by samifruit514** [kubernetes-helm/monocular#446]
Hello,

In our environment, we have to develop and deploy fast (CD context). This means when we build a chart and upload it into our chart repo, our instance of monocular should show it immediately in the choices so we can deploy it right away. Is there a reason why there is no way to refresh a repo or a chart from the repo from monocular based on a trigger system? A work around would be to set the cacheinterval to few seconds but I think it would be too resource intensive.

Is there any other workaround?

Thanks

**Comment by prydonius** [comment]
Hey @samifruit514, there's no way to do this right now as the syncs happen in a separate goroutine to the API server. Your best option is to reduce the cache refresh interval to something lower (https://github.com/kubernetes-helm/monocular/blob/master/deployment/monocular/values.yaml#L56). Monocular will not re-process charts it already knows about. It will only hit the index.yaml and process new charts/versions it finds (if any), so the impact is fairly low. A 1m interval might be fine.

**Comment by samifruit514** [comment]
Thanks for the feedback. Your solution is interesting. However, I made a PR for a feature where you can trigger a refresh of a single chart (all versions) of a single repo:

https://github.com/kubernetes-helm/monocular/pull/447

This is a draft. If it looks interesting for you, I could polish this PR

**Comment by samifruit514** [comment]
https://github.com/kubernetes-helm/monocular/pull/447 merged.

Thank you very much @prydonius
