### ISSUE TITLE
cannot find package "k8s.io/kubernetes/pkg/client/restclient" in any of

### ISSUE THREAD

**Issue by zhangxinZKCD** [kubernetes-helm/monocular#448]
hello
When I make build, I get an error that I cannot find a dependency：

**【log】**
data/helm/client/client.go:18:2: cannot find package "k8s.io/kubernetes/pkg/client/restclient" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/client/restclient (from $GOROOT)
	/go/src/k8s.io/kubernetes/pkg/client/restclient (from $GOPATH)
Makefile:37: recipe for target 'build' failed
make: *** [build] Error 1

root@a70d834d6ec4:/go# go get k8s.io/kubernetes/pkg/client/restclient
package k8s.io/kubernetes/pkg/client/restclient: cannot find package "k8s.io/kubernetes/pkg/client/restclient" in any of:
	/usr/local/go/src/k8s.io/kubernetes/pkg/client/restclient (from $GOROOT)
	/go/src/k8s.io/kubernetes/pkg/client/restclient (from $GOPATH)

**How can I solve this problem？**

**Comment by prydonius** [comment]
have you run `make bootstrap`?
