### ISSUE TITLE
cannot get any chart in homepage

### ISSUE THREAD

**Issue by kelvinblood** [kubernetes-helm/monocular#453]
I am new to monocular, trying several times for installation, but every time homepage cannot get any chart.

![20180522150347](https://user-images.githubusercontent.com/1147524/40347046-65b246e2-5dd1-11e8-8d43-05669c9d84cc.jpg)

The logs from ui is the access log with code 403, from api is just healthz access.

this is my install code:
`helm install monocular/monocular --name monocular --set controller.hostNetwork=true`

and I have tried with

`helm install monocular/monocular --name monocular --set controller.hostNetwork=true  -f custom.yaml`

> ingress:
>   hosts:
>   - monocular.xxx.org
> api:
>   config:
>     repos:
>       - name: stable
>         url: https://burdenbear.github.io/kube-charts-mirror
>         source: https://github.com/kubernetes/charts/tree/master/stable
>       - name: monocular
>         url: https://kubernetes-helm.github.io/monocular
>         source: https://github.com/kubernetes-helm/monocular/tree/master/charts

I use nfs pv like below:

> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: monocular-mongodb
> spec:
>   capacity:
>     storage: 8Gi
>   accessModes:
>     - ReadWriteOnce
>   persistentVolumeReclaimPolicy: Retain
>   mountOptions:
>     - hard
>     - nfsvers=4
>   nfs:
>     path: /monocular
>     server: xxx

ps: I cannot access ingress, so I just use ui:port for homepage.  Is this the point?

**Comment by duckzhouya** [comment]
I got the same problem as you.How did you solve this problem?
"Unexpected token < in JSON at position 0" showed in debug mode of chrome.

![screenshot from 2019-02-22 10-36-30](https://user-images.githubusercontent.com/6919644/53215938-d4345980-368d-11e9-8c70-1cc90a4fbe15.png)
