### ISSUE TITLE
no charts found for repo stable

### ISSUE THREAD

**Issue by somedayiamold** [kubernetes-helm/monocular#455]
No charts found from monocular after upgrading to 0.7.0, and it worked on 0.6.2
The log is found below:
2018/05/28 09:47:45 data.Charts AllFromRepo(stable) error (no charts found for repo stable
)
[negroni] 2018-05-28T09:47:45Z | 404 |   201.758µs | monocular.ddd.com | GET /v1/charts/stable 
[negroni] 2018-05-28T09:47:45Z | 200 |   1.343836ms | monocular.ddd.com | GET /v1/repos 
[negroni] 2018-05-28T09:47:45Z | 404 |   65.056µs | monocular.ddd.com | GET /auth/verify 

but some charts can be found in monocular-api container:
![image](https://user-images.githubusercontent.com/7919507/40609151-608b2d54-62a0-11e8-884e-b5baf6929af3.png)

**Comment by chz8494** [comment]
seeing same error, it's weird, sometimes api won't kickoff downloading charts at all, and then it gives this error which makes sense, but sometimes it downloads everything but still complain this error.

**Comment by somedayiamold** [comment]
ok, I will have a try once the fix is released.

**Comment by chz8494** [comment]
still same thing.
2018/05/31 15:07:01 data.Charts AllFromRepo(stable) error (no charts found for repo stable
)
[negroni] 2018-05-31T15:07:04Z | 200 | 	 726.981µs | 10.240.105.95 | GET /v1/repos 
[negroni] 2018-05-31T15:07:04Z | 404 | 	 363.24µs | 10.240.105.95 | GET /auth/verify 
[negroni] 2018-05-31T15:07:04Z | 200 | 	 1.339554ms | 10.240.105.95 | GET /v1/repos 
[negroni] 2018-05-31T15:07:04Z | 200 | 	 664.444µs | 10.240.105.95 | GET /v1/repos 
[negroni] 2018-05-31T15:07:05Z | 404 | 	 80.322µs | 10.240.105.95 | GET /auth/verify 
2018/05/31 15:07:05 data.Charts AllFromRepo(stable) error (no charts found for repo stable
)
[negroni] 2018-05-31T15:07:05Z | 404 | 	 811.863µs | 10.240.105.95 | GET /v1/charts/stable 
[negroni] 2018-05-31T15:07:05Z | 404 | 	 77.244µs | 10.240.105.95 | GET /auth/verify 
2018/05/31 15:07:05 data.Charts AllFromRepo(stable) error (no charts found for repo stable
)
[negroni] 2018-05-31T15:07:05Z | 404 | 	 219.409µs | 10.240.105.95 | GET /v1/charts/stable 
[negroni] 2018-05-31T15:07:06Z | 200 | 	 1.061847ms | 10.240.105.95 | GET /v1/repos 
[negroni] 2018-05-31T15:07:06Z | 404 | 	 88.524µs | 10.240.105.95 | GET /auth/verify 
2018/05/31 15:07:06 data.Charts AllFromRepo(stable) error (no charts found for repo stable
)

query for charts returns 200 though, but not listing anything on GUI
[negroni] 2018-05-31T15:05:35Z | 200 | 	 6.141344ms | 10.240.105.95 | GET /v1/charts 

stable folder contents
/cache/repo-data/stable#  ls
acs-engine-autoscaler/  coscale/                 gcloud-sqlproxy/       kapacitor/             mcrouter/                 nginx-ldapauth-proxy/    presto/                          rocketchat/             sumokube/
aerospike/              dask/                    gcp-night-king/        keel/                  mediawiki/                oauth2-proxy/            prometheus/                      sapho/                  sumologic-fluentd/
anchore-engine/         datadog/                 ghost/                 kibana/                memcached/                odoo/                    prometheus-cloudwatch-exporter/  schema-registry-ui/     superset/
artifactory/            dex/                     gocd/                  kong/                  metabase/                 opencart/                prometheus-mysql-exporter/       selenium/               sysdig/
artifactory-ha/         dmarc2logstash/          grafana/               kube2iam/              metallb/                  openebs/                 prometheus-node-exporter/        sematext-docker-agent/  tensorflow-notebook/
bitcoind/               docker-registry/         hackmd/                kube-ops-view/         minecraft/                openvpn/                 prometheus-postgres-exporter/    sensu/                  tensorflow-serving/
buildkite/              dokuwiki/                hadoop/                kubernetes-dashboard/  minio/                    orangehrm/               prometheus-pushgateway/          sentry/                 testlink/
burrow/                 drupal/                  heapster/              kube-slack/            mongodb/                  osclass/                 prometheus-rabbitmq-exporter/    seq/                    traefik/
centrifugo/             elastabot/               horovod/               kube-state-metrics/    mongodb-replicaset/       owncloud/                prometheus-redis-exporter/       signalfx-agent/         uchiwa/
cert-manager/           elastalert/              inbucket/              kubewatch/             moodle/                   pachyderm/               prometheus-to-sd/                sonarqube/              unbound/
chaoskube/              elasticsearch-exporter/  influxdb/              lamp/                  msoms/                    parse/                   quassel/                         sonatype-nexus/         verdaccio/
chartmuseum/            etcd-operator/           ipfs/                  linkerd/               mssql-linux/              percona/                 rabbitmq/                        spark/                  weave-cloud/
chronograf/             ethereum/                janusgraph/            locust/                mysql/                    percona-xtradb-cluster/  rabbitmq-ha/                     spartakus/              weave-scope/
cluster-autoscaler/     external-dns/            jasperreports/         luigi/                 namerd/                   phabricator/             redis/                           spinnaker/              wordpress/
cockroachdb/            factorio/                jenkins/               magento/               neo4j/                    phpbb/                   redis-ha/                        spotify-docker-gc/      zeppelin/
concourse/              filebeat/                joomla/                magic-namespace/       newrelic-infrastructure/  phpmyadmin/              redmine/                         stackdriver-exporter/   zetcd/
consul/                 fluent-bit/              k8s-spot-rescheduler/  mailhog/               nfs-server-provisioner/   postgresql/              rethinkdb/                       stolon/
coredns/                gcloud-endpoints/        kanister-operator/     mariadb/               nginx-ingress/            prestashop/              risk-advisor/                    suitecrm/

**Comment by somedayiamold** [comment]
@prydonius seems 0.7.1 does not fix the issue either, it just returns {"data": null} by /v1/charts

**Comment by prydonius** [comment]
Does the previous version of Monocular work fine? `helm install monocular/monocular --version 0.5.2`?

**Comment by somedayiamold** [comment]
@prydonius helm install monocular/monocular --version 0.6.2 works fine

**Comment by prydonius** [comment]
@samifruit514 any ideas, wondering if this might be related to some of your recent changes?

**Comment by vvangestel** [comment]
Our monocular (version 0.7.2) isn't downloading any chart at all. The api logs display the following error:
```
level=info msg="Using cache directory" path="/monocular/repo-data" 
level=info msg="periodic job ran and returned error (error unmarshaling JSON: json: cannot unmarshal string into Go value of type map[string]interface {})" 
```
