### ISSUE TITLE
Add nodeSelector, tolerations, affinity configuration to helm chart 

### ISSUE THREAD

**Issue by YunSangJun** [kubernetes-helm/monocular#459]
Our team wants to run monocular only at certain nodes. Helm 2.8.0+ also generate these configuration by default. The Kubernetes Official Chart Guide also recommends including this attribute.

Please refer to below branch for more information.
https://github.com/YunSangJun/monocular/tree/assign-pod-to-node

**Comment by prydonius** [comment]
@YunSangJun I'd be happy to accept a PR to add these, I unfortunately won't have the bandwidth to get to this anytime soon.

**Comment by cnpst-adm** [comment]
@prydonius I sent PR for this issue. Please review and merge.

https://github.com/kubernetes-helm/monocular/pull/460

**Comment by YunSangJun** [comment]
@prydonius I sent PR for this issue. Please review and merge.

https://github.com/kubernetes-helm/monocular/pull/460
