### ISSUE TITLE
API never goes into ready status

### ISSUE THREAD

**Issue by polinchw** [kubernetes-helm/monocular#463]
When installing with Helm the monocular api pods never go into ready status.

helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
monocular       1               Mon Jun  4 19:39:00 2018        DEPLOYED        monocular-0.6.1         default
nginx-ingress   1               Mon Jun  4 19:36:51 2018        DEPLOYED        nginx-ingress-0.20.1    default

NAME                                             READY     STATUS    RESTARTS   AGE
monocular-mongodb-5869685cb9-lch5s               1/1       Running   0          4m
**monocular-monocular-api-9b84c6478-kqgxg          0/1       Running   1          1m
monocular-monocular-api-9b84c6478-w462p          0/1       Running   2          2m**
monocular-monocular-prerender-698466ddc4-xdrwg   1/1       Running   0          4m
monocular-monocular-ui-6dc9ccc8d4-t29wn          1/1       Running   0          4m
monocular-monocular-ui-6dc9ccc8d4-vjssw          1/1       Running   0          4m
nginx-ingress-controller-d58cc6c47-jtssm         1/1       Running   0          6m
nginx-ingress-default-backend-9c5d6df7d-qkpnk    1/1       Running   0          6m

**Comment by prydonius** [comment]
It looks like those pods have only been running for 2m, it takes a few minutes for the API pods to get into the ready state.

**Comment by polinchw** [comment]
Kubernetes is killing the pod because it doesn't pass its heath check on time.  I've set the liveliness timeout in the values.yaml file to 600 seconds.  How long should it take for monocular to pull the data it needs before the api starts up?

**Comment by polinchw** [comment]
I was able to get monocular running.  It took about 45 mins to get the api to cache all the charts then it started.  The pods api keeps restarting itself until it passes the health check.  I'll close this issue.

 kubectl get pods -n default | grep mono
monocular-mongodb-75989ffc56-jp2pq                     1/1       Running            0          1h
monocular-monocular-api-57c89df4db-8wgt9               1/1       Running            20         1h
monocular-monocular-api-57c89df4db-mbzph               1/1       Running            12         1h
monocular-monocular-prerender-cdc9449bf-n7zsk          1/1       Running            0          1h
monocular-monocular-ui-5867c5bcf9-dv45p                1/1       Running            0          1h
monocular-monocular-ui-5867c5bcf9-mnqwx                1/1       Running            0          1h
