### ISSUE TITLE
monocular-api can't get charts from repos

### ISSUE THREAD

**Issue by FengyunPan2** [kubernetes-helm/monocular#469]
\# kubectl exec -it   monocular-monocular-api-54fdb9c4d8-2jw8z  -n kube-system  -- sh
/ # cat /monocular/config/monocular.yaml
mongodb:
  url: monocular-mongodb:27017
  database: monocular
cacheRefreshInterval: 3600
cors:
  allowed_headers:
  - content-type
  - x-xsrf-token
  allowed_origins:
  - ""
releasesEnabled: true
repos:
- name: chinac
  url: xxxxxxxxxxxxxxxxx
  source: https://github.com/kubernetes/charts/tree/master/stable
/ # exit
command terminated with exit code 130
\# kubectl logs  monocular-monocular-api-54fdb9c4d8-2jw8z  -n kube-system
time="2018-06-21T03:44:32Z" level=info msg="Configuration bootstrap init" configFile="/monocular/config/monocular.yaml" 
time="2018-06-21T03:44:32Z" level=info msg="Configuration file found!" 
time="2018-06-21T03:44:32Z" level=info msg="Loading CORS from config file" 
time="2018-06-21T03:44:32Z" level=info msg="Loading repositories from config file" 
time="2018-06-21T03:44:32Z" level=info msg="Configuration bootstrap finished" 
time="2018-06-21T03:44:32Z" level=info msg="Using cache directory" path="/monocular/repo-data" 
time="2018-06-21T03:45:02Z" level=warning msg="authentication is disabled" error="no signing key, ensure MONOCULAR_AUTH_SIGNING_KEY is set" 
time="2018-06-21T03:45:02Z" level=info msg="Started Monocular API server" addr=":8081" 
[negroni] 2018-06-21T03:45:35Z | 200 | 	 167.811µs | 10.100.70.12:8081 | GET /healthz 
[negroni] 2018-06-21T03:46:05Z | 200 | 	 94.775µs | 10.100.70.12:8081 | GET /healthz

**Comment by prydonius** [comment]
@FengyunPan2 I guess this is related to #470?
