### ISSUE TITLE
Failed to build monocular-api

### ISSUE THREAD

**Issue by FengyunPan2** [kubernetes-helm/monocular#471]
monocular]$ go build src/api/main.go 
\# github.com/kubernetes-helm/monocular/src/api/swagger/restapi/operations/charts
src/api/swagger/restapi/operations/charts/get_all_charts.go:41:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/charts/get_chart.go:41:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/charts/get_chart_version.go:41:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/charts/get_chart_versions.go:41:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/charts/get_charts_in_repo.go:45:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/charts/search_charts.go:41:11: cannot assign 3 values to 2 variables
\# github.com/kubernetes-helm/monocular/src/api/swagger/restapi/operations/releases
src/api/swagger/restapi/operations/releases/create_release.go:44:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/releases/delete_release.go:41:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/releases/get_all_releases.go:41:11: cannot assign 3 values to 2 variables
src/api/swagger/restapi/operations/releases/get_release.go:41:11: cannot assign 3 values to 2 variables
\# github.com/kubernetes-helm/monocular/vendor/k8s.io/helm/pkg/helm
vendor/k8s.io/helm/pkg/helm/option.go:389:9: undefined: metadata.NewContext
\# github.com/kubernetes-helm/monocular/vendor/golang.org/x/oauth2/google
vendor/golang.org/x/oauth2/google/sdk.go:79:15: undefined: internal.ParseINI

**Comment by prince-mishra** [comment]
I am getting the same error. @FengyunPan2 Can you please comment on how you got this fixed?

**Comment by prydonius** [comment]
FYI next week I plan to work on the changes outlined in https://github.com/helm/community/blob/master/proposals/monocular-1.0-improvements.md, the existing API server implementation will be replaced.

**Comment by prydonius** [comment]
@prince-mishra Monocular 1.0 plans to drop all support for in-cluster installations (see https://github.com/helm/community/blob/master/proposals/monocular-1.0-improvements.md#removing-in-cluster-support), it will focus on only having a read-only interface over chart repos. You might want to checkout http://github.com/kubeapps/kubeapps for what you're looking for.
