### ISSUE TITLE
The default resource limits applied to the 'api' is not enough getting OOM in pods

### ISSUE THREAD

**Issue by bzon** [kubernetes-helm/monocular#473]
__Problem__

I was just trying out monocular today and I keep getting OOM Error in the API pods. Can we consider increasing the defaults to avoid this type of issue when someone is trying out the quickstart guide? Considering that "someone" is new to kubernetes or helm.

The resource requests is going over 100%+ if someone will observe it.

__Proposed Change__

Increase the __api.resource.limits.memory__ to __526Mi__ and __api.resource.limits.cpu__ to __200__ in [default values](https://github.com/kubernetes-helm/monocular/blob/master/deployment/monocular/values.yaml).

**Comment by imroc** [comment]
![image](https://user-images.githubusercontent.com/7448852/42420763-68b008e2-82fd-11e8-92bf-2d11fa85bd75.png)
I got the same issue

**Comment by migmartri** [comment]
Thanks @bzon for the comment.

Based on your experience running monocular under the 512Mi limit, have you found that value enough for running a full chart import without any container restarts?
