### ISSUE TITLE
Monocular Chart Repository URI: Not a valid chart repository

### ISSUE THREAD

**Issue by pcgeek86** [kubernetes-helm/monocular#478]
Per the `README.md` directions, I tried to register the Helm chart repository for monocular, and received the following error:

```
➜  ~ helm repo add monocular https://helm.github.io/monocular
Error: Looks like "https://helm.github.io/monocular" is not a valid chart repository or cannot be reached: Failed to fetch https://helm.github.io/monocular/index.yaml : 404 Not Found
```

* Amazon EKS v1.10.3
* Helm v2.9.1

Any thoughts on how to resolve this?

**Comment by prydonius** [comment]
@pcgeek86 we're in the middle of a move to the Helm GitHub org hence why those docs were updated and are temporarily incorrect. The move should be completed today.

**Comment by pcgeek86** [comment]
Got it, someone provided me this URL, which worked: https://kubernetes-helm.github.io/monocular

**Comment by prydonius** [comment]
@pcgeek86 just be aware that that one may stop working when this repo moves to Helm

**Comment by pcgeek86** [comment]
@prydonius Sounds good, didn't realize there were big changes going on. Just trying to get up and running for now. Appreciate the heads up! Cheers

**Comment by prydonius** [comment]
@pcgeek86 this has now been transferred over. In case you're interested, this is due to Helm's move to a top-level project under the CNCF - see https://github.com/cncf/toc/blob/master/proposals/helm.adoc for more info!
